language: python

cache:
  directories:
    - $HOME/miniconda3

matrix:
  include:
    - name: Build against PyTorch < 1.0.0
      env: TORCH='pytorch<1.0.0'
    - name: Build against PyTorch >= 1.0.0
      env: TORCH='pytorch>=1.0.0'
  allow_failures:
    - name: Build against nightly PyTorch (allowed to fail)
      env: TORCH='pytorch-nightly'

before_install:
  - . ./scripts/install_miniconda.sh

install:
  - pip install --upgrade pip
  - conda install $TORCH -c pytorch
  - pip install -r requirements-dev.txt | grep 'Collecting\|Using cached\|Requirement already satisfied\| installed'
  - pip install -e . --no-deps

script:
  - black --check --diff geoopt
  - py.test -v --durations=0

after_success:
  - coveralls
