matrix:
  include:
    - os: linux
      dist: bionic
      language: sh
      python:
        - "3.6"
      # Perform the manual steps on Linux to install python3 and activate venv
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
        - bash $HOME/miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n test python=3.6 pip wheel
        - conda activate test
    - os: linux
      dist: bionic
      language: sh
      python:
        - "3.7"
      # Perform the manual steps on Linux to install python3 and activate venv
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
        - bash $HOME/miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n test python=3.7 pip wheel
        - conda activate test
    - os: osx
      language: sh
      python:
        - "3.6"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh
        - bash $HOME/miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n test python=3.6 pip wheel
        - conda activate test
    - os: osx
      language: sh
      python:
        - "3.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh
        - bash $HOME/miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -n test python=3.7 pip wheel
        - conda activate test
    - os: windows
      language: sh
      python:
        - "3.6"
      before_install:
        - choco install miniconda3
        - export PATH="/c/tools/miniconda3/bin:$PATH"
        - conda create -n test python=3.6 pip
        - conda activate test
    - os: windows
      language: sh
      python:
        - "3.7"
      before_install:
        - choco install miniconda3
        - export PATH="/c/tools/miniconda3/bin:$PATH"
        - conda create -n test python=3.7 pip
        - conda activate test
install:
  # Get newer pip and wheel for binary caching support
  - pip install --upgrade pip wheel
  - pip install -U -r requirements-dev.txt
  - pip install -e .
  - echo "hurray"
