language: python
python:
    - "3.6"

env:
  - PYTHON_VERSION=3.6 PYTORCH_CHANNEL='pytorch' PYTORCH_VERSION='=1.3.0' COVERAGE='--cov geoopt'
  - PYTHON_VERSION=3.6 PYTORCH_CHANNEL='pytorch' PYTORCH_VERSION='=1.2.0' COVERAGE=''
  - PYTHON_VERSION=3.6 PYTORCH_CHANNEL='pytorch-nightly' PYTORCH_VERSION='' COVERAGE=''

matrix:
  allow_failures:
    - env: PYTHON_VERSION=3.6 PYTORCH_CHANNEL='pytorch-nightly' PYTORCH_VERSION='' COVERAGE=''

before_install:
  - docker pull conda/miniconda3
  - docker --version

install:
  - make docker
  # Print conda details
  - docker run --rm geoopt:latest bash -c "conda info -a"
  # Print conda environment details
  - docker run --rm geoopt:latest bash -c "conda list && pip freeze"
  # install coverage if needed
  - if [[ $COVERAGE ]]; then pip install -r requirements-dev.txt; fi

script:
  - make docker-test

after_success:
  - echo $(pwd)
  - ls -la
  - if [[ $COVERAGE ]]; then coveralls; fi
