language: python
python:
    - "3.6"
cache:
  directories:
    - $HOME/miniconda3

env:
  - PYTHON_VERSION=3.6 PYTORCH='pytorch>=1.0.0' COVERAGE='--cov geoopt'
  - PYTHON_VERSION=3.6 PYTORCH='pytorch-nightly' COVERAGE=''

matrix:
  allow_failures:
    - env: PYTHON_VERSION=3.6 PYTORCH='pytorch-nightly' COVERAGE=''

before_install:
  - docker pull conda/miniconda3
  - docker --version

install:
  - . ./scripts/container.sh --build
  # Print conda details
  - docker run --rm geoopt:latest bash -c "conda info -a"
  # Print conda environment details
  - docker run --rm geoopt:latest bash -c "conda list && pip freeze"
  # install coverage if needed
  - if [[ $COVERAGE ]]; then pip install coveralls black; fi

script:
  - if [[ $COVERAGE ]]; then black --check --diff geoopt tests; fi
  - ./scripts/container.sh --test

after_success:
  - echo $(pwd)
  - ls -la
  - if [[ $COVERAGE ]]; then sed -i 's@/opt/geoopt@/home/travis/build/geoopt@g' .coverage && coveralls; fi
